<?xml version="1.0" encoding="utf-8"?><Database Name="LocalDb" Class="kutuphaneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\LocalDb.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Kutuphane.Properties.Settings" SettingsPropertyName="LocalDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Publisher" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="WriterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Borrow" Member="Borrows" ThisKey="Id" OtherKey="BookId" Type="Borrow" />
      <Association Name="BookType_Book" Member="BookType" ThisKey="TypeId" OtherKey="Id" Type="BookType" IsForeignKey="true" />
      <Association Name="Writer_Book" Member="Writer" ThisKey="WriterId" OtherKey="Id" Type="Writer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BookTypes" Member="BookTypes">
    <Type Name="BookType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Explanation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="BookType_Book" Member="Books" ThisKey="Id" OtherKey="TypeId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Borrows" Member="Borrows">
    <Type Name="Borrow">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EstimatedReturnDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MemberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Borrow" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="Member_Borrow" Member="Member" ThisKey="MemberId" OtherKey="Id" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SSN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NameSurname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MembershipStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BirthPlace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TelephoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Member_Borrow" Member="Borrows" ThisKey="Id" OtherKey="MemberId" Type="Borrow" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Writers" Member="Writers">
    <Type Name="Writer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameSurname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Biography" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Writer_Book" Member="Books" ThisKey="Id" OtherKey="WriterId" Type="Book" />
    </Type>
  </Table>
</Database>